on:
  push:
    branches:
      - 'feature/**'
  pull_request:

jobs:
  terraform-plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: terraform init
        run: terraform init -no-color 

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: TFLint
        run: |
          tflint --init
          tflint

      - name: Terraform Plan
        run: terraform plan -no-color | tee plan.out

      - name: Comment plan result to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.out

